### ISSUE TITLE
Add Plane Class

### ISSUE THREAD

**Issue by EdvardA1** [TheaNoteberg/Algorithms#6] opened 2022-03-02 15:53 UTC
https://mathworld.wolfram.com/Plane.html
Required for issue 42.
Some features in the plane class should include:
Create a plane by giving the Hessian Normal form input.
Create a plane by giving three points.
Create a plane by giving two lines.

**Comment by TheaNoteberg** [comment] 2022-03-03 09:27
Duplicate of issue #2

**Closed as completed** 2022-03-03 09:27 UTC
